branches:
  only:
  - travis
  - master
before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install sshpass
script:
  - pdflatex resume.tex
  - curl -T resume.pdf --user "johnlradford_iggaboo:$PAIR_PW" 'ftp://johnlradford.pairserver.com/'