branches:
  only:
  - master
before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install sshpass
script:
  - pdflatex resume.tex
after_success:
  - curl -T resume.pdf --user "$PAIR_USER:$PAIR_PW" 'ftp://johnlradford.pairserver.com/'