branches:
  only:
  - travis
  - master
before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-extra
script:
  - pdflatex resume.tex
  - curl -T resume.pdf --user "$SERVER_USER:$SERVER_PW" "$SERVER_URL"
