before_install:
  - sudo apt-get update
  - sudo apt-get install texlive-latex-extra
  - sudo apt-get install sshpass
script:
  - pdflatex resume.tex
after_success:
  - export SSHPASS=$PITT_PW
  - sshpass -e scp -o StrictHostKeyChecking=no resume.pdf "$PITT_USER@unixs.cssd.pitt.edu:public/html"